### PR TITLE
mmo-games: All minimum viable product features draft - 01

### PR DESCRIPTION
**Pull request by gtekle**
## What this PR does:
  - Fetches MMO Games data from an external API and displays them in the home page with a like button
  - A popup comments window with more data about a game where comments can be added is displayed upon comments button click
  - When the user clicks on the Like button of an item, the interaction is recorded in the Involvement API and the screen is updated.
  - When the user clicks on the "Comments" button, the Comments popup appears.
  - Home page header and navigation similar to the given mockup.
  - Home page footer similar to the given mockup.
  
## Presentation video
  - [Latest presentation video](https://drive.google.com/file/d/1iGspUNguWlb4UqfSOdgUJP4SyVcf1Ugn/view?usp=sharing)
  - [Previous presentation video](https://drive.google.com/file/d/1dekr65d3arSLH6k_x3qgNm5vygw5_JI_/view?usp=sharing)

## How to test it
  - clone the repository by running\
      `git clone https://github.com/gtekle/mmo-games.git`
  - navigate to the root folder\
      `cd mmo-games`
 - Install packages\
      `npm install`
 - add `.env` file to the root directory and copy paste the following code into this file.
        
    > API_KEY=dbb7593505mshdb2b499e2f3acf1p12c4c1jsn93ec8e29d6c6
    > INVOLVEMENT_API_BASE_URL=https://us-central1-involvement-api.cloudfunctions.net/capstoneApi/apps/
    > APP_ID=jR2b1a7YUQNXOQh80WK2

  - Run application using `webpack-dev-server`\
      `npm start`

## Details

### CODE REVIEW

**Review by er-contreras — CHANGES_REQUESTED** [review]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

almost there

## Required Changes ♻️

- [ ] All the members in the video should talk about the project.
- [ ] The video contains a highlight about a piece of the code the student finds interesting or is proud of making.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gtekle** [comment]
Hi @eri8-9, 
we have recorded another presentation as per the feedback you gave us.

**Review by Deepakdanger — APPROVED** [review]
**Hi @team**, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Your video link should be accessed. The video link should be `public` or make it accessed via `link`.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gtekle** [comment]
Hi @Deepakdanger 
Thank you and we are really sorry for the inconvenience with regard to the video link access. we have now rectified the issue.
thanks again.

**Pull request merged**
